config:
  database: false
  yml: true
database:
  host: "localhost"
  port: "3306"
  database: "crafting_tracker"
  user: "root"
  password: ""
  type: "mysql"
tracked-items:
  - DIAMOND_SWORD
  - IRON_PICKAXE
  - GOLDEN_APPLE
  - OAK_LOG
  - STONE_BRICK
